/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-20 01:57:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewCapsule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/link.html", out, false);
      out.write("\r\n");
      out.write("<script src=\"js/viewCapsule.js\" defer></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/viewCapsule.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class='watchWrap'>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"watchContents\">\r\n");
      out.write("			<!-- <img src=\"img/backgorund.jpg\" alt=\"\"> -->\r\n");
      out.write("			<div class=\"heart\">\r\n");
      out.write("				<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("				<span>10</span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"title\">\r\n");
      out.write("				<p>title</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"titleSlide\">\r\n");
      out.write("				<div class=\"swiper mySwiper4\">\r\n");
      out.write("					<div class=\"swiper-wrapper\">\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-slide\">\r\n");
      out.write("							<img src=\"img/backgorund.jpg\" alt=\"swiperImages\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"swiper-pagination\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"title_bottom_content\">\r\n");
      out.write("				<p>나는 이번 주제에 대해 곰곰이 생각해 보았다. 요즘 나의 최대 걱정. 솔직하게 써야 할지 고민했다. 이 글은\r\n");
      out.write("					많은 사람들이 볼 수 있는 글이다. 그러니 주제는 바이러스에 관한 걱정 등 대중적인 걱정일 법한 것으로 선택하려 했다.\r\n");
      out.write("					하지만 나의 이야기를 담지 않은 글은 진정한 나의 글이 아니라는 생각이 들어, 나의 진실된 나는 이번 주제에 대해 곰곰이\r\n");
      out.write("					생각해 보았다. 요즘 나의 최대 걱정. 솔직하게 써야 할지 고민했다. 이 글은 많은 사람들이 볼 수 있는 글이다. 그러니\r\n");
      out.write("					주제는 바이러스에 관한 걱정 등 대중적인 걱정일 법한 것으로 선택하려 했다. 하지만 나의 이야기를 담지 않은 글은 진정한\r\n");
      out.write("					나의 글이 아니라는 생각이 들어, 나의 진실된</p>\r\n");
      out.write("				<span>더보기 ...</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"chat\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>강유진</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>송유경</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>김대영</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>김현수</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>송택호</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img/ex.jpg\" alt=\"chatProfile\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"chat_info\">\r\n");
      out.write("							<h6>김나연</h6>\r\n");
      out.write("							<p>안녕하세요~~!!^ㅅ^ 안녕하세요~~!!^ㅅ^ 안녕하세요~~!!^ㅅ^ 안녕하세요~~!!^ㅅ^</p>\r\n");
      out.write("							<span class=\"reply\">답장하기</span> <span>지우기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat-heart\">\r\n");
      out.write("							<span><img src=\"img/pink_icon_heart.png\" alt=\"pinkHeart\"></span>\r\n");
      out.write("							<span>10</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"comment\">\r\n");
      out.write("				<figure>\r\n");
      out.write("					<img src=\"img/ex.jpg\" alt=\"commentImg\">\r\n");
      out.write("				</figure>\r\n");
      out.write("				<div class=\"input-wrapper\">\r\n");
      out.write("					<input type=\"text\" name=\"comment\" placeholder=\"댓글을 입력하세요\">\r\n");
      out.write("					<button type=\"button\" class=\"upload\">\r\n");
      out.write("						<img src=\"img/upArrow.png\" alt=\"업로드\">\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
