-- WHERE 절
SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';
SELECT * FROM EMPLOYEES WHERE SALARY >=15000;
SELECT * FROM EMPLOYEES WHERE SALARY < 10000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <>50; -- 같지 않음
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'STEVEN'; -- 저장된 데이터 값은 대소문자 구분