-- 시퀀스 (순차적으로 증가하는 값)
-- 보통 PK를 지정하는데 사용할 수 있음
SELECT * FROM USER_SEQUENCES;

-- 생성
CREATE SEQUENCE DEPTS_SEQ; -- 기본값으로 지정이 되면서 시퀀스 생성
DROP SEQUENCE DEPTS_SEQ;  -- 삭제

CREATE SEQUENCE DEPTS_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10
    MINVALUE 1
    NOCYCLE -- 시퀀스가 MAX에 도달했을 때 재사용 X
    NOCACHE -- 시퀀스는 메모리(캐시)에 두지 않음
;

SELECT * FROM DEPTS;
DROP TABLE DEPTS;

CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2) PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)
);
INSERT INTO DEPTS VALUES(DEPTS_SEQ.NEXTVAL,'A'); -- MAXVALUE에 도달하면, 더이상 사용 불가능
SELECT * FROM DEPTS;
-- 시퀀스 사용 방법 2가지
SELECT DEPTS_SEQ.CURRVAL FROM DUAL; -- NEXTVAL가 한번 실행이 되고난 이후에 확인 가능
SELECT DEPTS_SEQ.NEXTVAL FROM DUAL; -- 한번 NEXTVAL가 일어나면 후진은 불가

-- 시퀀스의 수정
ALTER SEQUENCE DEPTS_SEQ MAXVALUE 1000;
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY 10;

-- 시퀀스가 이미 테이블에서 사용중에 있으면, 시퀀스는 DROP하면 안됨
-- 주기적으로 시퀀스를 초기화 해야 할 경우
-- 시퀀스 증가값을 - 현재값으로 바꾸고
SELECT DEPTS_SEQ.CURRVAL FROM DUAL;
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY -10 MINVALUE 0;
-- 전진을 시킴
SELECT DEPTS_SEQ.NEXTVAL FROM DUAL;
-- 다시 시퀀스 증가값을 양수값으로 바꿔
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY 1;
-- 시퀀스 초기화
SELECT DEPTS_SEQ.NEXTVAL FROM DUAL;