-- 단일행 서브쿼리 : SELECT한 결과가 1행인 서브쿼리
-- 서브쿼리는 ()로 묶는다. 연산자보다는 오른쪽에 나옴

SELECT * 
FROM EMPLOYEES 
WHERE SALARY >= (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME= 'Nancy');

-- 직원번호가 103번인 사람과 동일한 직무를 가진사람

SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=103;

SELECT * 
FROM EMPLOYEES 
WHERE SALARY >= (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME= 'Nancy');
-- 주의할점 : 단일행 서브쿼리는 반드시 하나의 행을 리턴을 해야함
-- 서브쿼리가 반환하는 행이 여러행이라면, 다중행 연산자를 쓰면 됨
SELECT SALARY
FROM EMPLOYEES WHERE FIRST_NAME = 'David';

SELECT * FROM EMPLOYEES WHERE SALARY IN (SELECT SALARY
FROM EMPLOYEES WHERE FIRST_NAME = 'David');

-- 다중행 서브쿼리
-- > ANY: 최소값 4800 보다 큰 데이터
SELECT *
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='David');

-- < ANY : 최대값 9500 보다 작은 데이터
SELECT *
FROM EMPLOYEES
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='David');

-- > ALL : 최대값 9500보다 큰 데이터 
SELECT *
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='David');

-- < ALL : 최소값 4800보다 작은 데이터 
SELECT *
FROM EMPLOYEES
WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='David');

-- IN : 정확히 일치하는 데이터가 나옴
SELECT *
FROM EMPLOYEES
WHERE SALARY IN (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='David');


-- 스칼라 서브쿼리 : SELECT절에 들어오는 서브쿼리로 조인을 대체할 수 있음

SELECT FIRST_NAME,
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) DEPARTMENT_NAME
FROM EMPLOYEES E;

-- 스칼라 쿼리는 한번에 하나의 컬럼을 가지고 옴. 많은 열을 가지고 올때는 가독성이 떨어질 수 있음
SELECT FIRST_NAME,
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID),
       (SELECT MANAGER_ID FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID)
FROM EMPLOYEES E;

-- 스칼라 쿼리는 다른 테이블의 1개의 컬럼만 가지고 올때 조인보다 유리할 수 있음
-- 회원별 JOBS 테이블의 TITLE을 가지고 오고, 부서테이블의 부서명을 조회

