-- 제약조건 : 컬럼에 원치않는 데이터가 입력, 삭제 , 수정 되는 것을 방지하기 위한 조건
-- PRIMARY KEY : 테이블의 고유키, 중복 X, NULL X, PK는 테이블에 1개
-- UNIQUE : 중복 X, NULL O
-- NOT NULL : NULL을 허용하지 않음
-- FOREIGN KEY : 참조하는 테이블의 PK를 넣어놓은 컬럼, 중복O , NULL O
-- CHECK : 컬럼에 대한 데이터 제한(WHERE절과 유사)

--제약조건을 확인하는 명령문 OR 마우스로 확인
SELECT * FROM user_constraints;


-- 1ST (열레벨)
DROP TABLE DEPTS;
CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2)       CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)  CONSTRAINT DEPTS_DEPT_NAME_NN NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, -- 값이 들어오지 않을 떄 자동으로 지정되는 값
    DEPT_PHONE VARCHAR2(30) CONSTRAINT DPETS_DEPT_PHONE_UK UNIQUE,
    DEPT_GENDER CHAR(1)     CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)       CONSTRAINT DEPTS_LOCA_ID_FK REFERENCES LOCATIONS(LOCATION_ID)
);
DESC DEPTS;

-- CONSTRAINTS는 생략가능
DROP TABLE DEPTS;
CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2)       PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)  NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, -- 값이 들어오지 않을 떄 자동으로 지정되는 값
    DEPT_PHONE VARCHAR2(30) UNIQUE,
    DEPT_GENDER CHAR(1)     CHECK(DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)       REFERENCES LOCATIONS(LOCATION_ID)
);

INSERT INTO DEPTS(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID) 
VALUES(1,NULL,'010...','F',1700); -- NOT NULL제약 위배

INSERT INTO DEPTS(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID) 
VALUES(1,'HONG','010...','X',1700); -- CHECK 제약 위배

INSERT INTO DEPTS(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID) 
VALUES(1,'HONG','010...','F',100); -- FOREIGN KEY 제약 위배

INSERT INTO DEPTS(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID) 
VALUES(1,'HONG','010...','F',1700); 

INSERT INTO DEPTS(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID) 
VALUES(2,'HONG','010...','F',1700); -- UNIQUE 제약 위배 

-- 개체 무결성 : 기본키는 NOT NULL일 수 없고 중복될 수 없음 
-- 참조 무결성 : 참조하는 테이블의 기본키만 외래키의 컬럼에 들어갈 수 있음
-- 도메인 무결성 : CHECK, UNIQUE 제약내에서만 데이터가 들어갈 수 있음

-- 2ND - 테이블 레벨 제약조건
DROP TABLE DEPTS;

CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL,
    DEPT_DATE DATE         DEFAULT SYSDATE,
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4),
    CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY(DEPT_NO/*,DEPT_NAME*/), -- 슈퍼키 지정은 테이블레벨로 가능
    CONSTRAINT DEPTS_PHONE_UK UNIQUE(DEPT_PHONE),
    CONSTRAINT DEPTS_GENDER_CK CHECK (DEPT_GENDER IN ('F','M')),
    CONSTRAINT DPETS_LOCA_ID_FK FOREIGN KEY(LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID)
);


-- 3RD (제약조건의 추가 삭제), 수정은 없음
CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL,
    DEPT_DATE DATE         DEFAULT SYSDATE,
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4)
);



ALTER TABLE DEPTS ADD CONSTRAINT DEPT_NO_PK PRIMARY KEY(DEPT_NO); -- PK추가
ALTER TABLE DEPTS MODIFY DEPT_NAME VARCHAR(30) NOT NULL;-- NOT NULL은 MODIFY 구문으로 열 변경으로 추가
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE); -- UK 추가
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('F','M')); -- CK 추가
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_LOCA_ID_FK FOREIGN KEY(LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID); -- FK추가

-- 제약 조건의 삭제
ALTER TABLE DEPTS DROP PRIMARY KEY; -- 이렇게 지울수 있음
ALTER TABLE DEPTS DROP CONSTRAINT DEPT_LOCA_ID_FK;

-- 테이블의 제약조건을 SQL문으로 확인
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPTS';