-- 날짜 함수
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;

-- 날짜는 연산이 가능
SELECT SYSDATE+1,SYSDATE-1 FROM DUAL; - 날짜
SELECT SYSDATE-HIRE_DATE DAY FROM EMPLOYEES; - 일수
SELECT (SYSDATE- HIRE_DATE)/ 7  WEEK FROM EMPLOYEES; -- 주

-- 날짜 반올림, 절삭 ROUND, TRUNC
SELECT SYSDATE, ROUND(SYSDATE), TRUNC(SYSDATE) FROM DUAL;

SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL; - 년 기준으로 절삭
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL; - 월 기준으로 절삭

